# Generated by Django 2.2.16 on 2020-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='isFinished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='playoff',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='queue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
