# Generated by Django 2.2.16 on 2020-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0002_auto_20201124_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpoints',
            name='runs',
            field=models.CharField(max_length=30),
        ),
    ]
