# Generated by Django 2.2.16 on 2020-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0004_auto_20201207_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpoints',
            name='bonuses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
