# Generated by Django 2.2.16 on 2020-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0007_matchpoints_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpoints',
            name='fifth_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matchpoints',
            name='first_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matchpoints',
            name='fourth_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matchpoints',
            name='second_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matchpoints',
            name='seventh_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matchpoints',
            name='sixth_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matchpoints',
            name='third_run',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
