# Generated by Django 2.2.16 on 2020-12-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0008_auto_20201221_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpoints',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
