# Generated by Django 2.2.16 on 2020-12-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0009_matchpoints_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpoints',
            name='runs',
            field=models.IntegerField(),
        ),
    ]
