# Generated by Django 2.2.16 on 2020-10-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_teaminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(default='Test', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
