# Generated by Django 2.2.16 on 2021-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0004_team_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_photo',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
