# Generated by Django 2.2.16 on 2020-11-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teams', '0004_team_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.SmallIntegerField()),
                ('points', models.SmallIntegerField()),
                ('bonus', models.SmallIntegerField()),
                ('small_points', models.SmallIntegerField()),
                ('wins', models.SmallIntegerField()),
                ('draws', models.SmallIntegerField()),
                ('losers', models.SmallIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='Teams.Team')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_year', to='Teams.Year')),
            ],
            options={
                'ordering': ['points'],
                'unique_together': {('name', 'year')},
            },
        ),
    ]
