# Generated by Django 2.2 on 2019-05-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_teaminfo'),
        ('Riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riders.Rider')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Team')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Year')),
            ],
            options={
                'ordering': ['team'],
                'unique_together': {('rider', 'year', 'team')},
            },
        ),
    ]
