# Generated by Django 2.2 on 2019-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0002_riderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderinfo',
            name='junior',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
