# Generated by Django 2.2 on 2019-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0003_riderinfo_junior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderinfo',
            name='junior',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
