# Generated by Django 2.2.16 on 2020-10-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0004_auto_20190515_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rider',
            name='nationality',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
