# Generated by Django 2.2.16 on 2020-10-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0005_auto_20201011_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='birthday',
            field=models.DateField(default='1900-12-12'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='nationality',
            field=models.CharField(default='Poland', max_length=32),
        ),
    ]
