# Generated by Django 2.2.16 on 2021-01-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0006_auto_20201011_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='rider_photo_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
